kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: otel-demo-cribl
nodes:
- role: control-plane
  image: kindest/node:v1.29.2
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
  image: kindest/node:v1.29.2
- role: worker
  image: kindest/node:v1.29.2